"""
Scenario Generator Agent - LLM-Native Architecture.

Primary: LLM with RAG context generates creative, contextual scenarios.
Assist: Validator ensures business constraints, rules provide fallback seed scenarios.
Security: AgentSecurityGuard validates scenarios before persistence.
"""
import uuid
from datetime import UTC, datetime
from typing import Any

from app.agents.llm_agent import get_scenario_agent
from app.agents.rules import generate_scenarios_for_order
from app.agents.scenario_validator import get_validator
from app.agents.security import AgentSecurityGuard
from app.agents.state import PipelineState
from app.aws.dynamo_status import write_status_safe
from app.mcp.tools import write_decision_log, write_scenarios

# Security guard instance for scenario validation
_security_guard = AgentSecurityGuard()


def log_agent_step(
    pipeline_run_id: str,
    agent_name: str,
    input_summary: str,
    output_summary: str,
    confidence_score: float,
    rationale: str,
) -> None:
    """Helper to log agent decision step."""
    entry = {
        "log_id": str(uuid.uuid4()),
        "timestamp": datetime.now(UTC).isoformat(),
        "pipeline_run_id": pipeline_run_id,
        "agent_name": agent_name,
        "input_summary": input_summary,
        "output_summary": output_summary,
        "confidence_score": confidence_score,
        "rationale": rationale,
        "human_decision": "pending",
        "approver_id": None,
        "approver_note": None,
        "override_value": None,
    }
    write_decision_log.invoke({"entry": entry})


def _get_rag_context_for_scenario_gen(disruption: dict, orders: list) -> dict[str, Any]:
    """
    Get rich RAG context for scenario generation.
    
    Returns context even if LLM is not available - used to inform rules too.
    """
    try:
        from app.rag import get_knowledge_base

        kb = get_knowledge_base()
        if not kb.available:
            return {"rag_available": False}

        situation = f"{disruption.get('type', 'unknown')} disruption severity {disruption.get('severity', 3)} affecting {len(orders)} orders"

        context = kb.get_context_for_agent(
            agent_name="ScenarioGenerator",
            current_situation=situation,
            disruption_type=disruption.get("type"),
        )
        context["rag_available"] = True

        return context

    except Exception as e:
        print(f"RAG context retrieval failed: {e}")
        return {"rag_available": False, "error": str(e)}


def _generate_seed_scenarios(orders: list, disruption: dict, constraints: dict) -> list[dict]:
    """
    Generate seed scenarios using rules.
    
    These serve as:
    1. Baseline options in case LLM fails
    2. Examples to guide LLM generation
    3. Validation reference points
    """
    seeds = []
    for order in orders[:5]:  # Limit to avoid token explosion
        try:
            order_scenarios = generate_scenarios_for_order(order, disruption, constraints)
            seeds.extend(order_scenarios)
        except Exception as e:
            print(f"Seed generation failed for order {order.get('order_id')}: {e}")
    return seeds


def _build_enhanced_llm_prompt(
    disruption: dict,
    orders: list,
    constraints: dict,
    rag_context: dict,
    seed_scenarios: list,
) -> str:
    """
    Build an enhanced prompt that includes RAG context and seed scenarios.
    """
    # Format RAG context
    rag_section = ""
    if rag_context.get("rag_available"):
        rag_parts = []

        if rag_context.get("similar_disruptions"):
            rag_parts.append("HISTORICAL DISRUPTIONS (similar situations):")
            for d in rag_context["similar_disruptions"][:3]:
                rag_parts.append(f"  - {d.get('content', 'N/A')[:300]}")

        if rag_context.get("relevant_decisions"):
            rag_parts.append("\nPAST DECISIONS (what humans approved/rejected):")
            for d in rag_context["relevant_decisions"][:3]:
                rag_parts.append(f"  - {d.get('content', 'N/A')[:250]}")

        if rag_context.get("domain_knowledge"):
            rag_parts.append("\nDOMAIN KNOWLEDGE (policies & best practices):")
            for d in rag_context["domain_knowledge"][:2]:
                rag_parts.append(f"  - {d.get('content', 'N/A')[:200]}")

        if rag_parts:
            rag_section = "\n".join(rag_parts)

    # Format seed scenarios as examples
    seed_section = ""
    if seed_scenarios:
        seed_section = "\nBASELINE OPTIONS (generated by rules - you can improve on these):\n"
        for s in seed_scenarios[:3]:
            seed_section += f"  - {s.get('action_type', 'N/A')}: {s.get('plan_json', {}).get('summary', 'N/A')}\n"

    # Build prompt
    prompt = f"""
Analyze this supply chain disruption and generate intelligent response scenarios.

DISRUPTION EVENT:
- ID: {disruption.get('id', 'N/A')}
- Type: {disruption.get('type', 'unknown')}
- Severity: {disruption.get('severity', 3)}/5
- Details: {disruption.get('details', {})}

IMPACTED ORDERS ({len(orders)} total, showing first 5):
"""

    for order in orders[:5]:
        prompt += f"""
  Order {order.get('order_id', 'N/A')}:
    - Priority: {order.get('priority', 'standard')}
    - DC: {order.get('dc', 'N/A')}
    - Lines: {len(order.get('lines', []))} items
    - Ship by: {order.get('promised_ship_time', 'N/A')}
"""

    prompt += f"""
AVAILABLE RESOURCES:
- Inventory at other DCs: {len(constraints.get('available_inventory', []))} SKUs available
- Substitution rules: {len(constraints.get('substitution_rules', []))} approved substitutes
- Capacity status: {constraints.get('capacity', 'unknown')}
"""

    if rag_section:
        prompt += f"""

=== HISTORICAL CONTEXT FROM KNOWLEDGE BASE ===
{rag_section}
===============================================
"""

    if seed_section:
        prompt += seed_section

    prompt += """

INSTRUCTIONS:
1. Generate 2-4 creative scenarios PER impacted order
2. Consider the historical context - what worked before?
3. Prioritize options that minimize SLA risk while controlling cost
4. Include at least one "creative" option beyond standard delay/reroute/substitute
5. Be specific in your action plans - include concrete steps

Return JSON with this structure:
{
  "scenarios": [
    {
      "scenario_id": "uuid",
      "disruption_id": "from above",
      "order_id": "order ID",
      "action_type": "delay|reroute|substitute|resequence|expedite|split|partial_ship",
      "plan_json": {
        "summary": "One-line description",
        "what_happened": "Clear explanation of the disruption impact",
        "what_to_do": "Recommended action",
        "how_to_handle": "Step-by-step execution plan"
      },
      "score_json": {
        "cost_impact_usd": 0.00,
        "sla_risk": 0.0,
        "complexity": 1-5,
        "labor_impact_minutes": 30,
        "needs_approval": true/false
      },
      "llm_rationale": "Why this scenario makes sense given the context"
    }
  ],
  "reasoning_summary": "Brief explanation of your overall approach"
}
"""

    return prompt


def scenario_generator_node(state: PipelineState) -> dict[str, Any]:
    """
    Scenario Generator Agent node - LLM-Native Architecture.
    
    Flow:
    1. Get RAG context (always, regardless of LLM availability)
    2. Generate seed scenarios from rules (as baseline/examples)
    3. Call LLM with enhanced prompt including RAG + seeds
    4. Validate LLM output against business rules
    5. Fall back to seeds if LLM fails or produces invalid output
    
    Args:
        state: Current pipeline state
        
    Returns:
        State updates with scenarios data
    """
    pipeline_run_id = state["pipeline_run_id"]
    signal = state.get("signal", {})
    constraints = state.get("constraints", {})

    write_status_safe(pipeline_run_id, "scenario_generator", "started")

    try:
        impacted_orders = signal.get("impacted_orders", [])
        disruption = {
            "id": signal["disruption_id"],
            "type": signal["type"],
            "severity": signal["severity"],
            "details": signal["details"],
        }

        # Step 1: Get RAG context (always)
        rag_context = _get_rag_context_for_scenario_gen(disruption, impacted_orders)
        rag_available = rag_context.get("rag_available", False)

        # Step 2: Generate seed scenarios from rules
        seed_scenarios = _generate_seed_scenarios(impacted_orders, disruption, constraints)

        # Step 3: Try LLM with enhanced prompt
        all_scenarios = []
        used_llm = False
        llm_confidence = 0.0
        validation_summary = ""

        llm_agent = get_scenario_agent()
        if llm_agent.use_llm:
            try:
                # Generate scenarios using LLM (uses RAG context internally)
                llm_scenarios = llm_agent.generate_scenarios(
                    disruption=disruption,
                    impacted_orders=impacted_orders,
                    constraints=constraints,
                )

                if llm_scenarios:
                    # Step 4: Validate LLM output
                    validator = get_validator()
                    orders_by_id = {o["order_id"]: o for o in impacted_orders}

                    valid_scenarios, validation_results = validator.validate_batch(
                        llm_scenarios, orders_by_id, constraints, auto_correct=True
                    )

                    # Calculate validation stats
                    total_issues = sum(len(r.issues) for r in validation_results)
                    error_count = sum(1 for r in validation_results if r.has_errors)

                    if valid_scenarios:
                        all_scenarios = valid_scenarios
                        used_llm = True
                        llm_confidence = 0.9 - (error_count * 0.1)  # Reduce confidence for errors
                        validation_summary = f"validated {len(valid_scenarios)}/{len(llm_scenarios)}, {total_issues} issues"
                    else:
                        print("All LLM scenarios failed validation, using seeds")
                        validation_summary = f"all failed validation ({error_count} errors)"

            except Exception as e:
                print(f"LLM scenario generation failed: {e}")
                validation_summary = f"LLM error: {str(e)[:50]}"

        # Step 5: Fall back to seed scenarios if needed
        if not all_scenarios:
            all_scenarios = seed_scenarios
            used_llm = False
            llm_confidence = 0.0

        # Step 6: Security validation - validate all scenarios before persistence
        security_violations = []
        secure_scenarios = []
        for scenario in all_scenarios:
            security_result = _security_guard.validate_scenario_bounds(scenario)
            if security_result.passed:
                secure_scenarios.append(scenario)
            else:
                security_violations.extend(security_result.violations)
                print(f"Security check failed for scenario {scenario.get('scenario_id', 'N/A')}: {security_result.violations}")

        # Use only secure scenarios (fall back to seeds if all rejected)
        if secure_scenarios:
            all_scenarios = secure_scenarios
        elif seed_scenarios:
            print(f"All scenarios failed security, falling back to {len(seed_scenarios)} seed scenarios")
            all_scenarios = seed_scenarios

        # Ensure all scenarios have required fields
        for scenario in all_scenarios:
            scenario["used_llm"] = used_llm
            if "scenario_id" not in scenario:
                scenario["scenario_id"] = str(uuid.uuid4())
            if "status" not in scenario:
                scenario["status"] = "pending"

        # Persist scenarios to database
        if all_scenarios:
            result = write_scenarios.invoke({"scenarios": all_scenarios})
            created_count = result.get("created", 0)
        else:
            created_count = 0

        # Build detailed rationale
        if used_llm:
            if rag_available:
                reasoning_mode = "LLM + RAG (historical context enhanced)"
            else:
                reasoning_mode = "LLM (no RAG context available)"
        else:
            reasoning_mode = "deterministic rules (LLM unavailable or validation failed)"

        rationale = f"Generated {len(all_scenarios)} scenarios using {reasoning_mode}."
        if validation_summary:
            rationale += f" Validation: {validation_summary}."
        if security_violations:
            rationale += f" Security: {len(security_violations)} violations filtered."
        if rag_available and rag_context.get("similar_disruptions"):
            rationale += f" Referenced {len(rag_context['similar_disruptions'])} similar historical disruptions."

        # Log decision
        log_agent_step(
            pipeline_run_id=pipeline_run_id,
            agent_name="Scenario Generator",
            input_summary=f"{len(impacted_orders)} orders, severity {disruption.get('severity', 3)}",
            output_summary=f"{len(all_scenarios)} scenarios ({created_count} persisted), {'LLM+RAG' if used_llm and rag_available else 'LLM' if used_llm else 'rules'}",
            confidence_score=max(0.7, llm_confidence if used_llm else 0.8),
            rationale=rationale,
        )

        write_status_safe(
            pipeline_run_id,
            "scenario_generator",
            "completed",
            {
                "scenarios_generated": len(all_scenarios),
                "scenarios_persisted": created_count,
                "used_llm": used_llm,
                "rag_enhanced": rag_available,
                "security_violations": len(security_violations),
            },
        )

        return {
            "scenarios": all_scenarios,
            "step": "scenario_generator",
            "scenario_generation_metadata": {
                "used_llm": used_llm,
                "rag_available": rag_available,
                "seed_count": len(seed_scenarios),
                "final_count": len(all_scenarios),
                "security_validated": True,
                "security_violations_filtered": len(security_violations),
            },
        }

    except Exception as e:
        write_status_safe(
            pipeline_run_id, "scenario_generator", "failed", {"error": str(e)}
        )
        return {
            "error": f"Scenario generator failed: {str(e)}",
            "step": "error",
        }
